# flake8: noqa

# import apis into api package
from hostafrica_sdk_python.api.backups_api import BackupsApi
from hostafrica_sdk_python.api.console_access_api import ConsoleAccessApi
from hostafrica_sdk_python.api.dns_api import DNSApi
from hostafrica_sdk_python.api.firewall_api import FirewallApi
from hostafrica_sdk_python.api.monitoring_api import MonitoringApi
from hostafrica_sdk_python.api.power_management_api import PowerManagementApi
from hostafrica_sdk_python.api.security_api import SecurityApi
from hostafrica_sdk_python.api.service_management_api import ServiceManagementApi
from hostafrica_sdk_python.api.snapshots_api import SnapshotsApi
from hostafrica_sdk_python.api.user_management_api import UserManagementApi
from hostafrica_sdk_python.api.vps_management_api import VPSManagementApi

