# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ha_sdk_python.models.catalogue_currency import CatalogueCurrency
from ha_sdk_python.models.catalogue_group import CatalogueGroup
from ha_sdk_python.models.catalogue_product import CatalogueProduct
from typing import Optional, Set
from typing_extensions import Self

class CatalogueData(BaseModel):
    """
    Top-level data payload for the GetCatalogue response. When product_id is specified, product is populated instead of groups.
    """ # noqa: E501
    currency: CatalogueCurrency
    groups: Optional[List[CatalogueGroup]] = Field(default=None, description="Product groups with nested products, plans, and config options. Present when no product_id filter is applied.")
    product: Optional[CatalogueProduct] = None
    __properties: ClassVar[List[str]] = ["currency", "groups", "product"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CatalogueData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CatalogueData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": CatalogueCurrency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "groups": [CatalogueGroup.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "product": CatalogueProduct.from_dict(obj["product"]) if obj.get("product") is not None else None
        })
        return _obj


