# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ha_sdk_python.models.create_order_items import CreateOrderItems
from ha_sdk_python.models.create_order_total import CreateOrderTotal
from ha_sdk_python.models.order_warning import OrderWarning
from ha_sdk_python.models.payment_error import PaymentError
from ha_sdk_python.models.payment_status import PaymentStatus
from typing import Optional, Set
from typing_extensions import Self

class CreateOrderResponseData(BaseModel):
    """
    Response data for a successful or pending order
    """ # noqa: E501
    order_id: StrictInt = Field(description="Order identifier")
    invoice_id: StrictInt = Field(description="Invoice identifier for this order")
    order_number: StrictStr = Field(description="Human-readable order reference number")
    total: CreateOrderTotal
    promo_applied: Optional[StrictStr] = Field(default=None, description="Promotional code that was applied")
    payment_method: StrictStr = Field(description="Payment method used (e.g. stripe)")
    payment_status: PaymentStatus
    items: CreateOrderItems
    payment_error: Optional[PaymentError] = None
    warnings: Optional[List[OrderWarning]] = Field(default=None, description="Warnings present when non-critical issues occurred (e.g. autorenew deferred)")
    __properties: ClassVar[List[str]] = ["order_id", "invoice_id", "order_number", "total", "promo_applied", "payment_method", "payment_status", "items", "payment_error", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrderResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of items
        if self.items:
            _dict['items'] = self.items.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_error
        if self.payment_error:
            _dict['payment_error'] = self.payment_error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrderResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "order_id": obj.get("order_id"),
            "invoice_id": obj.get("invoice_id"),
            "order_number": obj.get("order_number"),
            "total": CreateOrderTotal.from_dict(obj["total"]) if obj.get("total") is not None else None,
            "promo_applied": obj.get("promo_applied"),
            "payment_method": obj.get("payment_method"),
            "payment_status": obj.get("payment_status"),
            "items": CreateOrderItems.from_dict(obj["items"]) if obj.get("items") is not None else None,
            "payment_error": PaymentError.from_dict(obj["payment_error"]) if obj.get("payment_error") is not None else None,
            "warnings": [OrderWarning.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        })
        return _obj


