# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DayOfWeek(str, Enum):
    """
    Day of week enum
    """

    """
    allowed enum values
    """
    MON = 'mon'
    TUE = 'tue'
    WED = 'wed'
    THU = 'thu'
    FRI = 'fri'
    SAT = 'sat'
    SUN = 'sun'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DayOfWeek from a JSON string"""
        return cls(json.loads(json_str))


