# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DnsRecordInfo(BaseModel):
    """
    A DNS record within a zone.  Record values are normalized to a flat `content` string. Structured record types use additional top-level fields; the proxy maps these to upstream `data` / `rdata_raw` shapes:  - **A / AAAA**: `content` is the IP address (`data.address`). - **CNAME**: `content` is the target hostname (`data.cname`). - **TXT**: `content` is the text value (`data.txtdata`). - **NS**: `content` is the nameserver hostname (`data.nsdname`). - **MX**: `content` is the mail exchange hostname; `priority` is the MX preference   (`data.exchange`, `data.preference`). - **SRV**: `content` is the target hostname; `priority`, `weight`, and `port` are the   SRV parameters (`data.target`, `data.priority`, `data.weight`, `data.port`).  When upstream returns structured `rdata_raw` without a string `rdata` value, `content` and the type-specific fields are derived from `rdata_raw`.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Record identifier")
    name: Optional[StrictStr] = Field(default=None, description="Record host/name (e.g. @, www, mail)")
    type: Optional[StrictStr] = Field(default=None, description="Record type (e.g. A, AAAA, CNAME, MX, TXT, NS, SRV)")
    content: Optional[StrictStr] = Field(default=None, description="Primary record value: IP address (A/AAAA), hostname (CNAME/NS/MX/SRV), or text (TXT)")
    ttl: Optional[StrictInt] = Field(default=None, description="Time-to-live in seconds")
    priority: Optional[StrictInt] = Field(default=None, description="MX preference when type is MX; SRV priority when type is SRV")
    weight: Optional[StrictInt] = Field(default=None, description="SRV weight when type is SRV")
    port: Optional[StrictInt] = Field(default=None, description="SRV port when type is SRV")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "content", "ttl", "priority", "weight", "port"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DnsRecordInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DnsRecordInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "content": obj.get("content"),
            "ttl": obj.get("ttl"),
            "priority": obj.get("priority"),
            "weight": obj.get("weight"),
            "port": obj.get("port")
        })
        return _obj


