# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DnsBackend(str, Enum):
    """
    Upstream DNS management backend for a zone.  - `dns_manager` — WHMCS DNS Manager - `directadmin` — DirectAdmin DNS
    """

    """
    allowed enum values
    """
    DNS_MANAGER = 'dns_manager'
    DIRECTADMIN = 'directadmin'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DnsBackend from a JSON string"""
        return cls(json.loads(json_str))


