# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DnsRecordMutationRecord(BaseModel):
    """
    DNS record fields for add, edit, or delete via DNSManager.  See `DnsRecordInfo` for how `content` and structured fields map to upstream record data. Delete requires only `id`, `name`, and `type`.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Record line/id from get-dns-zone-details; required for edit and delete")
    name: Optional[StrictStr] = Field(default=None, description="Record host/name (e.g. @, www, mail); required for add")
    type: Optional[StrictStr] = Field(default=None, description="Record type (e.g. A, AAAA, CNAME, MX, TXT, NS, SRV); required for add")
    content: Optional[StrictStr] = Field(default=None, description="Primary record value; required for add and edit. Meaning depends on type — see DnsRecordInfo")
    ttl: Optional[StrictInt] = Field(default=None, description="Time-to-live in seconds; defaults to 3600 on add when omitted")
    priority: Optional[StrictInt] = Field(default=None, description="MX preference when type is MX; SRV priority when type is SRV")
    weight: Optional[StrictInt] = Field(default=None, description="SRV weight when type is SRV")
    port: Optional[StrictInt] = Field(default=None, description="SRV port when type is SRV; required for add and edit when type is SRV")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "content", "ttl", "priority", "weight", "port"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DnsRecordMutationRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DnsRecordMutationRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "content": obj.get("content"),
            "ttl": obj.get("ttl"),
            "priority": obj.get("priority"),
            "weight": obj.get("weight"),
            "port": obj.get("port")
        })
        return _obj


