# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FirewallRule(BaseModel):
    """
    Firewall rule structure
    """ # noqa: E501
    digest: StrictStr = Field(description="SHA1 digest of the rule")
    pos: StrictInt = Field(description="Position/priority of the rule")
    type: StrictStr = Field(description="Rule type (in, out)")
    action: StrictStr = Field(description="Action to perform (ACCEPT, REJECT, DROP)")
    iface: StrictStr = Field(description="Network interface name")
    enable: StrictInt = Field(description="Whether the rule is enabled (1=enabled, 0=disabled)")
    comment: Optional[StrictStr] = Field(default=None, description="Comment/description for the rule")
    source: Optional[StrictStr] = Field(default=None, description="Source address/network")
    dest: Optional[StrictStr] = Field(default=None, description="Destination address/network")
    proto: Optional[StrictStr] = Field(default=None, description="Protocol (tcp, udp, icmp, etc)")
    dport: Optional[StrictStr] = Field(default=None, description="Destination port")
    sport: Optional[StrictStr] = Field(default=None, description="Source port")
    macro: Optional[StrictStr] = Field(default=None, description="Firewall macro name")
    log: Optional[StrictStr] = Field(default=None, description="Log level")
    __properties: ClassVar[List[str]] = ["digest", "pos", "type", "action", "iface", "enable", "comment", "source", "dest", "proto", "dport", "sport", "macro", "log"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FirewallRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FirewallRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "digest": obj.get("digest"),
            "pos": obj.get("pos"),
            "type": obj.get("type"),
            "action": obj.get("action"),
            "iface": obj.get("iface"),
            "enable": obj.get("enable"),
            "comment": obj.get("comment"),
            "source": obj.get("source"),
            "dest": obj.get("dest"),
            "proto": obj.get("proto"),
            "dport": obj.get("dport"),
            "sport": obj.get("sport"),
            "macro": obj.get("macro"),
            "log": obj.get("log")
        })
        return _obj


