# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InvoiceTransaction(BaseModel):
    """
    A payment or refund transaction recorded against an invoice
    """ # noqa: E501
    id: StrictInt = Field(description="Transaction identifier")
    gateway: Optional[StrictStr] = Field(default=None, description="Payment gateway identifier")
    var_date: Optional[StrictStr] = Field(default=None, description="Transaction date (ISO 8601 or upstream date string)", alias="date")
    description: Optional[StrictStr] = Field(default=None, description="Transaction description")
    amount_in: Optional[StrictStr] = Field(default=None, description="Amount received as a decimal string")
    fees: Optional[StrictStr] = Field(default=None, description="Gateway fees as a decimal string")
    amount_out: Optional[StrictStr] = Field(default=None, description="Amount paid out (e.g. refund) as a decimal string")
    trans_id: Optional[StrictStr] = Field(default=None, description="Gateway transaction reference")
    __properties: ClassVar[List[str]] = ["id", "gateway", "date", "description", "amount_in", "fees", "amount_out", "trans_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "gateway": obj.get("gateway"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "amount_in": obj.get("amount_in"),
            "fees": obj.get("fees"),
            "amount_out": obj.get("amount_out"),
            "trans_id": obj.get("trans_id")
        })
        return _obj


