# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from ha_sdk_python.models.power_task import PowerTask
from ha_sdk_python.models.power_task_dialog_rules import PowerTaskDialogRules
from typing import Optional, Set
from typing_extensions import Self

class PowerTaskListResponseData(BaseModel):
    """
    Response data for power task list operation
    """ # noqa: E501
    message: StrictStr = Field(description="Status message indicating the result")
    tasks: List[PowerTask] = Field(description="List of power tasks")
    available_actions: List[StrictStr] = Field(description="Available power actions")
    available_job_types: List[StrictStr] = Field(description="Available job types")
    dialog_rules: PowerTaskDialogRules
    __properties: ClassVar[List[str]] = ["message", "tasks", "available_actions", "available_job_types", "dialog_rules"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PowerTaskListResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tasks (list)
        _items = []
        if self.tasks:
            for _item_tasks in self.tasks:
                if _item_tasks:
                    _items.append(_item_tasks.to_dict())
            _dict['tasks'] = _items
        # override the default output from pydantic by calling `to_dict()` of dialog_rules
        if self.dialog_rules:
            _dict['dialog_rules'] = self.dialog_rules.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PowerTaskListResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "tasks": [PowerTask.from_dict(_item) for _item in obj["tasks"]] if obj.get("tasks") is not None else None,
            "available_actions": obj.get("available_actions"),
            "available_job_types": obj.get("available_job_types"),
            "dialog_rules": PowerTaskDialogRules.from_dict(obj["dialog_rules"]) if obj.get("dialog_rules") is not None else None
        })
        return _obj


