# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ha_sdk_python.models.backup_creation_info import BackupCreationInfo
from ha_sdk_python.models.backup_item import BackupItem
from ha_sdk_python.models.backup_mode import BackupMode
from ha_sdk_python.models.compression_method import CompressionMethod
from typing import Optional, Set
from typing_extensions import Self

class ServiceBackupsResponseData(BaseModel):
    """
    Response data for service backups operation
    """ # noqa: E501
    message: StrictStr = Field(description="Status message indicating the result")
    backups: List[BackupItem] = Field(description="List of backups for the service")
    quota_total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total backup quota (null if unlimited)")
    quota_used: Union[StrictFloat, StrictInt] = Field(description="Used backup quota")
    quota_unit: StrictStr = Field(description="Unit for quota measurements (e.g., GiB)")
    available_compress_methods: List[CompressionMethod] = Field(description="Available compression methods for creating backups")
    available_modes: List[BackupMode] = Field(description="Available backup modes")
    backup_is_creating: StrictBool = Field(description="Whether a backup is currently being created")
    backup_creation: Optional[BackupCreationInfo] = None
    __properties: ClassVar[List[str]] = ["message", "backups", "quota_total", "quota_used", "quota_unit", "available_compress_methods", "available_modes", "backup_is_creating", "backup_creation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceBackupsResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backups (list)
        _items = []
        if self.backups:
            for _item_backups in self.backups:
                if _item_backups:
                    _items.append(_item_backups.to_dict())
            _dict['backups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_compress_methods (list)
        _items = []
        if self.available_compress_methods:
            for _item_available_compress_methods in self.available_compress_methods:
                if _item_available_compress_methods:
                    _items.append(_item_available_compress_methods.to_dict())
            _dict['available_compress_methods'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_modes (list)
        _items = []
        if self.available_modes:
            for _item_available_modes in self.available_modes:
                if _item_available_modes:
                    _items.append(_item_available_modes.to_dict())
            _dict['available_modes'] = _items
        # override the default output from pydantic by calling `to_dict()` of backup_creation
        if self.backup_creation:
            _dict['backup_creation'] = self.backup_creation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceBackupsResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "backups": [BackupItem.from_dict(_item) for _item in obj["backups"]] if obj.get("backups") is not None else None,
            "quota_total": obj.get("quota_total"),
            "quota_used": obj.get("quota_used"),
            "quota_unit": obj.get("quota_unit"),
            "available_compress_methods": [CompressionMethod.from_dict(_item) for _item in obj["available_compress_methods"]] if obj.get("available_compress_methods") is not None else None,
            "available_modes": [BackupMode.from_dict(_item) for _item in obj["available_modes"]] if obj.get("available_modes") is not None else None,
            "backup_is_creating": obj.get("backup_is_creating"),
            "backup_creation": BackupCreationInfo.from_dict(obj["backup_creation"]) if obj.get("backup_creation") is not None else None
        })
        return _obj


