# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ha_sdk_python.models.snapshot_job import SnapshotJob
from ha_sdk_python.models.snapshot_job_limits import SnapshotJobLimits
from typing import Optional, Set
from typing_extensions import Self

class SnapshotJobListResponseData(BaseModel):
    """
    Response data for snapshot job list operation
    """ # noqa: E501
    message: StrictStr = Field(description="Status message indicating the result")
    jobs: List[SnapshotJob] = Field(description="List of snapshot jobs")
    limits: SnapshotJobLimits
    allowed_periods: Optional[List[StrictStr]] = Field(default=None, description="Allowed schedule periods for snapshot jobs")
    __properties: ClassVar[List[str]] = ["message", "jobs", "limits", "allowed_periods"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnapshotJobListResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in jobs (list)
        _items = []
        if self.jobs:
            for _item_jobs in self.jobs:
                if _item_jobs:
                    _items.append(_item_jobs.to_dict())
            _dict['jobs'] = _items
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnapshotJobListResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "jobs": [SnapshotJob.from_dict(_item) for _item in obj["jobs"]] if obj.get("jobs") is not None else None,
            "limits": SnapshotJobLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "allowed_periods": obj.get("allowed_periods")
        })
        return _obj


