# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateDomainNameserversRequestContent(BaseModel):
    """
    UpdateDomainNameserversRequestContent
    """ # noqa: E501
    domain_id: StrictStr = Field(description="Domain service id - must be sent as a string")
    ns1: StrictStr = Field(description="Primary nameserver hostname")
    ns2: StrictStr = Field(description="Secondary nameserver hostname")
    ns3: Optional[StrictStr] = Field(default=None, description="Optional tertiary nameserver hostname")
    ns4: Optional[StrictStr] = Field(default=None, description="Optional quaternary nameserver hostname")
    ns5: Optional[StrictStr] = Field(default=None, description="Optional fifth nameserver hostname")
    __properties: ClassVar[List[str]] = ["domain_id", "ns1", "ns2", "ns3", "ns4", "ns5"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateDomainNameserversRequestContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateDomainNameserversRequestContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain_id": obj.get("domain_id"),
            "ns1": obj.get("ns1"),
            "ns2": obj.get("ns2"),
            "ns3": obj.get("ns3"),
            "ns4": obj.get("ns4"),
            "ns5": obj.get("ns5")
        })
        return _obj


