# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ha_sdk_python.models.day_of_week import DayOfWeek
from ha_sdk_python.models.power_task_job_type import PowerTaskJobType
from typing import Optional, Set
from typing_extensions import Self

class UpdatePowerTaskRequestContent(BaseModel):
    """
    UpdatePowerTaskRequestContent
    """ # noqa: E501
    service_id: StrictStr = Field(description="Service ID - must be sent as a string")
    task_id: StrictInt = Field(description="Power task ID to update")
    power_task_action: Optional[StrictStr] = Field(default=None, description="Power action to perform (start, stop, restart)")
    start_date: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Start date in Y-m-d format (e.g., 2026-03-25)")
    description: Optional[StrictStr] = Field(default=None, description="Description of the power task")
    start_time: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Start time in HH:MM or HH:MM:SS format")
    end_date: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="End date in Y-m-d format (e.g., 2026-12-31)")
    end_time: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="End time in HH:MM or HH:MM:SS format")
    job_type: Optional[PowerTaskJobType] = None
    job_time: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Job execution time in HH:MM or HH:MM:SS format")
    job_hour: Optional[Annotated[int, Field(le=23, strict=True, ge=0)]] = Field(default=None, description="Job hour (alternative to job_time)")
    job_minutes: Optional[Annotated[int, Field(le=59, strict=True, ge=0)]] = Field(default=None, description="Job minutes (alternative to job_time)")
    days: Optional[List[DayOfWeek]] = Field(default=None, description="Days of the week for weekly jobs")
    __properties: ClassVar[List[str]] = ["service_id", "task_id", "power_task_action", "start_date", "description", "start_time", "end_date", "end_time", "job_type", "job_time", "job_hour", "job_minutes", "days"]

    @field_validator('start_date')
    def start_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d{4}-\d{2}-\d{2}$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}$/")
        return value

    @field_validator('start_time')
    def start_time_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$", value):
            raise ValueError(r"must validate the regular expression /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/")
        return value

    @field_validator('end_date')
    def end_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d{4}-\d{2}-\d{2}$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}$/")
        return value

    @field_validator('end_time')
    def end_time_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$", value):
            raise ValueError(r"must validate the regular expression /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/")
        return value

    @field_validator('job_time')
    def job_time_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$", value):
            raise ValueError(r"must validate the regular expression /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdatePowerTaskRequestContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdatePowerTaskRequestContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "service_id": obj.get("service_id"),
            "task_id": obj.get("task_id"),
            "power_task_action": obj.get("power_task_action"),
            "start_date": obj.get("start_date"),
            "description": obj.get("description"),
            "start_time": obj.get("start_time"),
            "end_date": obj.get("end_date"),
            "end_time": obj.get("end_time"),
            "job_type": obj.get("job_type"),
            "job_time": obj.get("job_time"),
            "job_hour": obj.get("job_hour"),
            "job_minutes": obj.get("job_minutes"),
            "days": obj.get("days")
        })
        return _obj


