# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ha_sdk_python.models.billing_cycle import BillingCycle
from typing import Optional, Set
from typing_extensions import Self

class ValidatePricingProduct(BaseModel):
    """
    A single product line item in a validate pricing request
    """ # noqa: E501
    pid: StrictInt = Field(description="Product ID")
    billing_cycle: BillingCycle
    plan_id: StrictInt = Field(description="Plan ID for the selected product configuration")
    hostname: Optional[StrictStr] = Field(default=None, description="Hostname to assign to the service")
    config_options: Optional[Any] = Field(description="Configuration options as a free-form map (option_id -> value)")
    __properties: ClassVar[List[str]] = ["pid", "billing_cycle", "plan_id", "hostname", "config_options"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidatePricingProduct from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if config_options (nullable) is None
        # and model_fields_set contains the field
        if self.config_options is None and "config_options" in self.model_fields_set:
            _dict['config_options'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidatePricingProduct from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pid": obj.get("pid"),
            "billing_cycle": obj.get("billing_cycle"),
            "plan_id": obj.get("plan_id"),
            "hostname": obj.get("hostname"),
            "config_options": obj.get("config_options")
        })
        return _obj


