# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class VpsConfigResponseData(BaseModel):
    """
    Response data for VPS configuration retrieval
    """ # noqa: E501
    message: StrictStr = Field(description="Status message indicating the result")
    hostname: Optional[StrictStr] = Field(default=None, description="Hostname of the VPS")
    is_kvm: Optional[StrictBool] = Field(default=None, description="Whether the VPS uses KVM virtualisation")
    sshkeys_enabled: Optional[StrictBool] = Field(default=None, description="Whether SSH key management is enabled for this VPS")
    available_boot_order: Optional[Any] = Field(default=None, description="Available boot order options keyed by device identifier")
    boot_order0: Optional[StrictStr] = Field(default=None, description="Primary boot order slot (device identifier, or null)", alias="bootOrder0")
    boot_order1: Optional[StrictStr] = Field(default=None, description="Secondary boot order slot (device identifier, or null)", alias="bootOrder1")
    boot_order2: Optional[StrictStr] = Field(default=None, description="Tertiary boot order slot (device identifier, or null)", alias="bootOrder2")
    sshkeys: Optional[StrictStr] = Field(default=None, description="Current SSH key(s) configured on the VPS (cloud-init)")
    __properties: ClassVar[List[str]] = ["message", "hostname", "is_kvm", "sshkeys_enabled", "available_boot_order", "bootOrder0", "bootOrder1", "bootOrder2", "sshkeys"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VpsConfigResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if available_boot_order (nullable) is None
        # and model_fields_set contains the field
        if self.available_boot_order is None and "available_boot_order" in self.model_fields_set:
            _dict['available_boot_order'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VpsConfigResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "hostname": obj.get("hostname"),
            "is_kvm": obj.get("is_kvm"),
            "sshkeys_enabled": obj.get("sshkeys_enabled"),
            "available_boot_order": obj.get("available_boot_order"),
            "bootOrder0": obj.get("bootOrder0"),
            "bootOrder1": obj.get("bootOrder1"),
            "bootOrder2": obj.get("bootOrder2"),
            "sshkeys": obj.get("sshkeys")
        })
        return _obj


