# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API

    The version of the OpenAPI document: 1.1.0 - 2026-07-16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class VpsAvailableFeatures(BaseModel):
    """
    Available features for the VPS
    """ # noqa: E501
    power_start: StrictBool = Field(description="Can start the VPS")
    power_stop: StrictBool = Field(description="Can stop the VPS")
    power_reboot: StrictBool = Field(description="Can reboot the VPS")
    power_shutdown: StrictBool = Field(description="Can shutdown the VPS")
    novnc_console: StrictBool = Field(description="Has noVNC console access")
    backups: StrictBool = Field(description="Has backup capabilities")
    backup_jobs: StrictBool = Field(description="Has backup jobs feature")
    backup_schedule: StrictBool = Field(description="Has backup schedule feature")
    firewall: StrictBool = Field(description="Has firewall feature")
    reinstall: StrictBool = Field(description="Can reinstall OS")
    change_hostname: StrictBool = Field(description="Can change hostname")
    change_iso_image: StrictBool = Field(description="Can change ISO image")
    network_stats: StrictBool = Field(description="Has network statistics feature")
    graphs: StrictBool = Field(description="Has graphs feature")
    __properties: ClassVar[List[str]] = ["power_start", "power_stop", "power_reboot", "power_shutdown", "novnc_console", "backups", "backup_jobs", "backup_schedule", "firewall", "reinstall", "change_hostname", "change_iso_image", "network_stats", "graphs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VpsAvailableFeatures from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VpsAvailableFeatures from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "power_start": obj.get("power_start"),
            "power_stop": obj.get("power_stop"),
            "power_reboot": obj.get("power_reboot"),
            "power_shutdown": obj.get("power_shutdown"),
            "novnc_console": obj.get("novnc_console"),
            "backups": obj.get("backups"),
            "backup_jobs": obj.get("backup_jobs"),
            "backup_schedule": obj.get("backup_schedule"),
            "firewall": obj.get("firewall"),
            "reinstall": obj.get("reinstall"),
            "change_hostname": obj.get("change_hostname"),
            "change_iso_image": obj.get("change_iso_image"),
            "network_stats": obj.get("network_stats"),
            "graphs": obj.get("graphs")
        })
        return _obj


