# coding: utf-8

# flake8: noqa

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BackupsApi",
    "ConsoleAccessApi",
    "DNSApi",
    "FirewallApi",
    "MonitoringApi",
    "PowerManagementApi",
    "SecurityApi",
    "ServiceManagementApi",
    "SnapshotsApi",
    "UserManagementApi",
    "VPSManagementApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AllowedFeaturesResponseData",
    "BackupCreateResponseData",
    "BackupCreationInfo",
    "BackupItem",
    "BackupMode",
    "BackupSchedule",
    "BackupScheduleListResponseData",
    "BadRequestError",
    "BadRequestErrorResponseContent",
    "CatalogueConfigOption",
    "CatalogueConfigSuboption",
    "CatalogueCurrency",
    "CatalogueData",
    "CatalogueGroup",
    "CataloguePlan",
    "CatalogueProduct",
    "ChangePasswordInput",
    "ChangePasswordOutput",
    "ChangePasswordRequestContent",
    "ChangePasswordResponseContent",
    "CompressionMethod",
    "CompressionType",
    "CreateBackupInput",
    "CreateBackupOutput",
    "CreateBackupRequestContent",
    "CreateBackupResponseContent",
    "CreateBackupScheduleInput",
    "CreateBackupScheduleOutput",
    "CreateBackupScheduleRequestContent",
    "CreateBackupScheduleResponseContent",
    "CreateFirewallRuleInput",
    "CreateFirewallRuleOutput",
    "CreateFirewallRuleRequestContent",
    "CreateFirewallRuleResponseContent",
    "CreateNotificationInput",
    "CreateNotificationOutput",
    "CreateNotificationRequestContent",
    "CreateNotificationResponseContent",
    "CreateOrderDomainItem",
    "CreateOrderInput",
    "CreateOrderItems",
    "CreateOrderOutput",
    "CreateOrderProduct",
    "CreateOrderProductItem",
    "CreateOrderRequestContent",
    "CreateOrderResponseContent",
    "CreateOrderResponseData",
    "CreateOrderTotal",
    "CreatePowerTaskInput",
    "CreatePowerTaskOutput",
    "CreatePowerTaskRequestContent",
    "CreatePowerTaskResponseContent",
    "CreateRdnsRecordInput",
    "CreateRdnsRecordOutput",
    "CreateRdnsRecordRequestContent",
    "CreateRdnsRecordResponseContent",
    "CreateRdnsRecordResponseData",
    "CreateSnapshotInput",
    "CreateSnapshotOutput",
    "CreateSnapshotRequestContent",
    "CreateSnapshotResponseContent",
    "DeleteBackupInput",
    "DeleteBackupOutput",
    "DeleteBackupRequestContent",
    "DeleteBackupResponseContent",
    "DeleteBackupScheduleInput",
    "DeleteBackupScheduleOutput",
    "DeleteBackupScheduleRequestContent",
    "DeleteBackupScheduleResponseContent",
    "DeleteFirewallRuleInput",
    "DeleteFirewallRuleOutput",
    "DeleteFirewallRuleRequestContent",
    "DeleteFirewallRuleResponseContent",
    "DeleteNotificationInput",
    "DeleteNotificationOutput",
    "DeleteNotificationRequestContent",
    "DeleteNotificationResponseContent",
    "DeletePowerTaskInput",
    "DeletePowerTaskOutput",
    "DeletePowerTaskRequestContent",
    "DeletePowerTaskResponseContent",
    "DeleteRdnsRecordInput",
    "DeleteRdnsRecordOutput",
    "DeleteRdnsRecordRequestContent",
    "DeleteRdnsRecordResponseContent",
    "DeleteSnapshotInput",
    "DeleteSnapshotOutput",
    "DeleteSnapshotRequestContent",
    "DeleteSnapshotResponseContent",
    "EditBackupScheduleInput",
    "EditBackupScheduleOutput",
    "EditBackupScheduleRequestContent",
    "EditBackupScheduleResponseContent",
    "FirewallListResponseData",
    "FirewallMoveDirection",
    "FirewallMoveResponseData",
    "FirewallOption",
    "FirewallRule",
    "FirewallRuleAction",
    "FirewallRuleType",
    "ForbiddenError",
    "ForbiddenErrorResponseContent",
    "GetCatalogueInput",
    "GetCatalogueOutput",
    "GetCatalogueRequestContent",
    "GetCatalogueResponseContent",
    "GetNoVncConsoleInput",
    "GetNoVncConsoleOutput",
    "GetNoVncConsoleRequestContent",
    "GetNoVncConsoleResponseContent",
    "GetOsTemplateDetailsInput",
    "GetOsTemplateDetailsOutput",
    "GetOsTemplateDetailsRequestContent",
    "GetOsTemplateDetailsResponseContent",
    "GetOsTemplateDetailsResponseData",
    "GetPrivateSshKeyInput",
    "GetPrivateSshKeyOutput",
    "GetPrivateSshKeyRequestContent",
    "GetPrivateSshKeyResponseContent",
    "GetPublicSshKeyInput",
    "GetPublicSshKeyOutput",
    "GetPublicSshKeyRequestContent",
    "GetPublicSshKeyResponseContent",
    "GetVpsConfigInput",
    "GetVpsConfigOutput",
    "GetVpsConfigRequestContent",
    "GetVpsConfigResponseContent",
    "GetVpsDetailsInput",
    "GetVpsDetailsOutput",
    "GetVpsDetailsRequestContent",
    "GetVpsDetailsResponseContent",
    "InternalServiceError",
    "InternalServiceErrorResponseContent",
    "InvalidStateError",
    "InvalidStateErrorResponseContent",
    "ListAllowedFeaturesInput",
    "ListAllowedFeaturesOutput",
    "ListAllowedFeaturesRequestContent",
    "ListAllowedFeaturesResponseContent",
    "ListBackupSchedulesInput",
    "ListBackupSchedulesOutput",
    "ListBackupSchedulesRequestContent",
    "ListBackupSchedulesResponseContent",
    "ListBackupsInput",
    "ListBackupsOutput",
    "ListBackupsRequestContent",
    "ListBackupsResponseContent",
    "ListFirewallRulesInput",
    "ListFirewallRulesOutput",
    "ListFirewallRulesRequestContent",
    "ListFirewallRulesResponseContent",
    "ListIsosInput",
    "ListIsosOutput",
    "ListIsosRequestContent",
    "ListIsosResponseContent",
    "ListIsosResponseData",
    "ListNotificationsInput",
    "ListNotificationsOutput",
    "ListNotificationsRequestContent",
    "ListNotificationsResponseContent",
    "ListOrdersOutput",
    "ListOrdersResponseContent",
    "ListOrdersResponseData",
    "ListOsTemplatesInput",
    "ListOsTemplatesOutput",
    "ListOsTemplatesRequestContent",
    "ListOsTemplatesResponseContent",
    "ListOsTemplatesResponseData",
    "ListPowerTasksInput",
    "ListPowerTasksOutput",
    "ListPowerTasksRequestContent",
    "ListPowerTasksResponseContent",
    "ListRdnsRecordsOutput",
    "ListRdnsRecordsResponseContent",
    "ListRdnsResponseData",
    "ListReinstallOsInput",
    "ListReinstallOsOutput",
    "ListReinstallOsRequestContent",
    "ListReinstallOsResponseContent",
    "ListReinstallOsResponseData",
    "ListSnapshotsInput",
    "ListSnapshotsOutput",
    "ListSnapshotsRequestContent",
    "ListSnapshotsResponseContent",
    "ListVpsServicesData",
    "ListVpsServicesOutput",
    "ListVpsServicesResponseContent",
    "MountIsoInput",
    "MountIsoOutput",
    "MountIsoRequestContent",
    "MountIsoResponseContent",
    "MoveFirewallRuleInput",
    "MoveFirewallRuleOutput",
    "MoveFirewallRuleRequestContent",
    "MoveFirewallRuleResponseContent",
    "NoVncConsoleDetails",
    "NoVncConsoleResponseData",
    "Notification",
    "NotificationCreateResponseData",
    "NotificationDialogRules",
    "NotificationListResponseData",
    "NotificationStatus",
    "OperationStatus",
    "Order",
    "OrderLastAttempt",
    "OrderWarning",
    "OsImage",
    "PaymentError",
    "PaymentStatus",
    "PowerTask",
    "PowerTaskCreateResponseData",
    "PowerTaskDialogRules",
    "PowerTaskListResponseData",
    "PublicSshKeyResponseData",
    "RdnsAvailableItem",
    "RdnsPool",
    "RdnsRecord",
    "RebootVpsInput",
    "RebootVpsOutput",
    "RebootVpsRequestContent",
    "RebootVpsResponseContent",
    "ResourceNotFoundError",
    "ResourceNotFoundErrorResponseContent",
    "RestoreBackupInput",
    "RestoreBackupOutput",
    "RestoreBackupRequestContent",
    "RestoreBackupResponseContent",
    "RetryPaymentInput",
    "RetryPaymentOutput",
    "RetryPaymentRequestContent",
    "RetryPaymentResponseContent",
    "RetryPaymentResponseData",
    "RetryPaymentTotal",
    "RollbackSnapshotInput",
    "RollbackSnapshotOutput",
    "RollbackSnapshotRequestContent",
    "RollbackSnapshotResponseContent",
    "ServiceBackupsResponseData",
    "ServiceSnapshotsResponseData",
    "ServiceUnavailableError",
    "ServiceUnavailableErrorResponseContent",
    "ShutdownVpsInput",
    "ShutdownVpsOutput",
    "ShutdownVpsRequestContent",
    "ShutdownVpsResponseContent",
    "SnapshotCreateResponseData",
    "SnapshotItem",
    "SshKeyDetails",
    "StartVpsInput",
    "StartVpsOutput",
    "StartVpsRequestContent",
    "StartVpsResponseContent",
    "StopVpsInput",
    "StopVpsOutput",
    "StopVpsRequestContent",
    "StopVpsResponseContent",
    "SuspendVpsInput",
    "SuspendVpsOutput",
    "SuspendVpsRequestContent",
    "SuspendVpsResponseContent",
    "TerminateVpsInput",
    "TerminateVpsOutput",
    "TerminateVpsRequestContent",
    "TerminateVpsResponseContent",
    "TooManyRequestsError",
    "TooManyRequestsErrorResponseContent",
    "TriggerReinstallInput",
    "TriggerReinstallOutput",
    "TriggerReinstallRequestContent",
    "TriggerReinstallResponseContent",
    "TriggerReinstallResponseData",
    "UnauthorizedError",
    "UnauthorizedErrorResponseContent",
    "UnsuspendVpsInput",
    "UnsuspendVpsOutput",
    "UnsuspendVpsRequestContent",
    "UnsuspendVpsResponseContent",
    "UpdateFirewallRuleInput",
    "UpdateFirewallRuleOutput",
    "UpdateFirewallRuleRequestContent",
    "UpdateFirewallRuleResponseContent",
    "UpdateNotificationInput",
    "UpdateNotificationOutput",
    "UpdateNotificationRequestContent",
    "UpdateNotificationResponseContent",
    "UpdatePowerTaskInput",
    "UpdatePowerTaskOutput",
    "UpdatePowerTaskRequestContent",
    "UpdatePowerTaskResponseContent",
    "UpdateSnapshotInput",
    "UpdateSnapshotOutput",
    "UpdateSnapshotRequestContent",
    "UpdateSnapshotResponseContent",
    "UpdateSshKeysInput",
    "UpdateSshKeysOutput",
    "UpdateSshKeysRequestContent",
    "UpdateSshKeysResponseContent",
    "UpdateVpsConfigInput",
    "UpdateVpsConfigOutput",
    "UpdateVpsConfigRequestContent",
    "UpdateVpsConfigResponseContent",
    "UserChangePasswordDetails",
    "UserChangePasswordInput",
    "UserChangePasswordOutput",
    "UserChangePasswordRequestContent",
    "UserChangePasswordResponseContent",
    "UserChangePasswordResponseData",
    "ValidatePricingBase",
    "ValidatePricingBreakdown",
    "ValidatePricingConfigItem",
    "ValidatePricingCurrency",
    "ValidatePricingDiscount",
    "ValidatePricingInput",
    "ValidatePricingOutput",
    "ValidatePricingPlanConfig",
    "ValidatePricingPlanPricing",
    "ValidatePricingPriceRange",
    "ValidatePricingProduct",
    "ValidatePricingProductResult",
    "ValidatePricingProrata",
    "ValidatePricingRequestContent",
    "ValidatePricingResponseContent",
    "ValidatePricingResponseData",
    "ValidatePricingSummary",
    "ValidatePricingSummaryRecurring",
    "ValidationError",
    "ValidationErrorResponseContent",
    "VpsAvailableFeatures",
    "VpsBandwidthInfo",
    "VpsConfigResponseData",
    "VpsCpuInfo",
    "VpsCredentials",
    "VpsDetailsResponse",
    "VpsDiskInfo",
    "VpsMemoryInfo",
    "VpsNetworkRate",
    "VpsOsInfo",
    "VpsServiceInfo",
    "VpsSimpleActionResponseData",
    "VpsVmInfo",
]

# import apis into sdk package
from hostafrica_sdk_python.api.backups_api import BackupsApi as BackupsApi
from hostafrica_sdk_python.api.console_access_api import ConsoleAccessApi as ConsoleAccessApi
from hostafrica_sdk_python.api.dns_api import DNSApi as DNSApi
from hostafrica_sdk_python.api.firewall_api import FirewallApi as FirewallApi
from hostafrica_sdk_python.api.monitoring_api import MonitoringApi as MonitoringApi
from hostafrica_sdk_python.api.power_management_api import PowerManagementApi as PowerManagementApi
from hostafrica_sdk_python.api.security_api import SecurityApi as SecurityApi
from hostafrica_sdk_python.api.service_management_api import ServiceManagementApi as ServiceManagementApi
from hostafrica_sdk_python.api.snapshots_api import SnapshotsApi as SnapshotsApi
from hostafrica_sdk_python.api.user_management_api import UserManagementApi as UserManagementApi
from hostafrica_sdk_python.api.vps_management_api import VPSManagementApi as VPSManagementApi

# import ApiClient
from hostafrica_sdk_python.api_response import ApiResponse as ApiResponse
from hostafrica_sdk_python.api_client import ApiClient as ApiClient
from hostafrica_sdk_python.configuration import Configuration as Configuration
from hostafrica_sdk_python.exceptions import OpenApiException as OpenApiException
from hostafrica_sdk_python.exceptions import ApiTypeError as ApiTypeError
from hostafrica_sdk_python.exceptions import ApiValueError as ApiValueError
from hostafrica_sdk_python.exceptions import ApiKeyError as ApiKeyError
from hostafrica_sdk_python.exceptions import ApiAttributeError as ApiAttributeError
from hostafrica_sdk_python.exceptions import ApiException as ApiException

# import models into sdk package
from hostafrica_sdk_python.models.allowed_features_response_data import AllowedFeaturesResponseData as AllowedFeaturesResponseData
from hostafrica_sdk_python.models.backup_create_response_data import BackupCreateResponseData as BackupCreateResponseData
from hostafrica_sdk_python.models.backup_creation_info import BackupCreationInfo as BackupCreationInfo
from hostafrica_sdk_python.models.backup_item import BackupItem as BackupItem
from hostafrica_sdk_python.models.backup_mode import BackupMode as BackupMode
from hostafrica_sdk_python.models.backup_schedule import BackupSchedule as BackupSchedule
from hostafrica_sdk_python.models.backup_schedule_list_response_data import BackupScheduleListResponseData as BackupScheduleListResponseData
from hostafrica_sdk_python.models.bad_request_error import BadRequestError as BadRequestError
from hostafrica_sdk_python.models.bad_request_error_response_content import BadRequestErrorResponseContent as BadRequestErrorResponseContent
from hostafrica_sdk_python.models.catalogue_config_option import CatalogueConfigOption as CatalogueConfigOption
from hostafrica_sdk_python.models.catalogue_config_suboption import CatalogueConfigSuboption as CatalogueConfigSuboption
from hostafrica_sdk_python.models.catalogue_currency import CatalogueCurrency as CatalogueCurrency
from hostafrica_sdk_python.models.catalogue_data import CatalogueData as CatalogueData
from hostafrica_sdk_python.models.catalogue_group import CatalogueGroup as CatalogueGroup
from hostafrica_sdk_python.models.catalogue_plan import CataloguePlan as CataloguePlan
from hostafrica_sdk_python.models.catalogue_product import CatalogueProduct as CatalogueProduct
from hostafrica_sdk_python.models.change_password_input import ChangePasswordInput as ChangePasswordInput
from hostafrica_sdk_python.models.change_password_output import ChangePasswordOutput as ChangePasswordOutput
from hostafrica_sdk_python.models.change_password_request_content import ChangePasswordRequestContent as ChangePasswordRequestContent
from hostafrica_sdk_python.models.change_password_response_content import ChangePasswordResponseContent as ChangePasswordResponseContent
from hostafrica_sdk_python.models.compression_method import CompressionMethod as CompressionMethod
from hostafrica_sdk_python.models.compression_type import CompressionType as CompressionType
from hostafrica_sdk_python.models.create_backup_input import CreateBackupInput as CreateBackupInput
from hostafrica_sdk_python.models.create_backup_output import CreateBackupOutput as CreateBackupOutput
from hostafrica_sdk_python.models.create_backup_request_content import CreateBackupRequestContent as CreateBackupRequestContent
from hostafrica_sdk_python.models.create_backup_response_content import CreateBackupResponseContent as CreateBackupResponseContent
from hostafrica_sdk_python.models.create_backup_schedule_input import CreateBackupScheduleInput as CreateBackupScheduleInput
from hostafrica_sdk_python.models.create_backup_schedule_output import CreateBackupScheduleOutput as CreateBackupScheduleOutput
from hostafrica_sdk_python.models.create_backup_schedule_request_content import CreateBackupScheduleRequestContent as CreateBackupScheduleRequestContent
from hostafrica_sdk_python.models.create_backup_schedule_response_content import CreateBackupScheduleResponseContent as CreateBackupScheduleResponseContent
from hostafrica_sdk_python.models.create_firewall_rule_input import CreateFirewallRuleInput as CreateFirewallRuleInput
from hostafrica_sdk_python.models.create_firewall_rule_output import CreateFirewallRuleOutput as CreateFirewallRuleOutput
from hostafrica_sdk_python.models.create_firewall_rule_request_content import CreateFirewallRuleRequestContent as CreateFirewallRuleRequestContent
from hostafrica_sdk_python.models.create_firewall_rule_response_content import CreateFirewallRuleResponseContent as CreateFirewallRuleResponseContent
from hostafrica_sdk_python.models.create_notification_input import CreateNotificationInput as CreateNotificationInput
from hostafrica_sdk_python.models.create_notification_output import CreateNotificationOutput as CreateNotificationOutput
from hostafrica_sdk_python.models.create_notification_request_content import CreateNotificationRequestContent as CreateNotificationRequestContent
from hostafrica_sdk_python.models.create_notification_response_content import CreateNotificationResponseContent as CreateNotificationResponseContent
from hostafrica_sdk_python.models.create_order_domain_item import CreateOrderDomainItem as CreateOrderDomainItem
from hostafrica_sdk_python.models.create_order_input import CreateOrderInput as CreateOrderInput
from hostafrica_sdk_python.models.create_order_items import CreateOrderItems as CreateOrderItems
from hostafrica_sdk_python.models.create_order_output import CreateOrderOutput as CreateOrderOutput
from hostafrica_sdk_python.models.create_order_product import CreateOrderProduct as CreateOrderProduct
from hostafrica_sdk_python.models.create_order_product_item import CreateOrderProductItem as CreateOrderProductItem
from hostafrica_sdk_python.models.create_order_request_content import CreateOrderRequestContent as CreateOrderRequestContent
from hostafrica_sdk_python.models.create_order_response_content import CreateOrderResponseContent as CreateOrderResponseContent
from hostafrica_sdk_python.models.create_order_response_data import CreateOrderResponseData as CreateOrderResponseData
from hostafrica_sdk_python.models.create_order_total import CreateOrderTotal as CreateOrderTotal
from hostafrica_sdk_python.models.create_power_task_input import CreatePowerTaskInput as CreatePowerTaskInput
from hostafrica_sdk_python.models.create_power_task_output import CreatePowerTaskOutput as CreatePowerTaskOutput
from hostafrica_sdk_python.models.create_power_task_request_content import CreatePowerTaskRequestContent as CreatePowerTaskRequestContent
from hostafrica_sdk_python.models.create_power_task_response_content import CreatePowerTaskResponseContent as CreatePowerTaskResponseContent
from hostafrica_sdk_python.models.create_rdns_record_input import CreateRdnsRecordInput as CreateRdnsRecordInput
from hostafrica_sdk_python.models.create_rdns_record_output import CreateRdnsRecordOutput as CreateRdnsRecordOutput
from hostafrica_sdk_python.models.create_rdns_record_request_content import CreateRdnsRecordRequestContent as CreateRdnsRecordRequestContent
from hostafrica_sdk_python.models.create_rdns_record_response_content import CreateRdnsRecordResponseContent as CreateRdnsRecordResponseContent
from hostafrica_sdk_python.models.create_rdns_record_response_data import CreateRdnsRecordResponseData as CreateRdnsRecordResponseData
from hostafrica_sdk_python.models.create_snapshot_input import CreateSnapshotInput as CreateSnapshotInput
from hostafrica_sdk_python.models.create_snapshot_output import CreateSnapshotOutput as CreateSnapshotOutput
from hostafrica_sdk_python.models.create_snapshot_request_content import CreateSnapshotRequestContent as CreateSnapshotRequestContent
from hostafrica_sdk_python.models.create_snapshot_response_content import CreateSnapshotResponseContent as CreateSnapshotResponseContent
from hostafrica_sdk_python.models.delete_backup_input import DeleteBackupInput as DeleteBackupInput
from hostafrica_sdk_python.models.delete_backup_output import DeleteBackupOutput as DeleteBackupOutput
from hostafrica_sdk_python.models.delete_backup_request_content import DeleteBackupRequestContent as DeleteBackupRequestContent
from hostafrica_sdk_python.models.delete_backup_response_content import DeleteBackupResponseContent as DeleteBackupResponseContent
from hostafrica_sdk_python.models.delete_backup_schedule_input import DeleteBackupScheduleInput as DeleteBackupScheduleInput
from hostafrica_sdk_python.models.delete_backup_schedule_output import DeleteBackupScheduleOutput as DeleteBackupScheduleOutput
from hostafrica_sdk_python.models.delete_backup_schedule_request_content import DeleteBackupScheduleRequestContent as DeleteBackupScheduleRequestContent
from hostafrica_sdk_python.models.delete_backup_schedule_response_content import DeleteBackupScheduleResponseContent as DeleteBackupScheduleResponseContent
from hostafrica_sdk_python.models.delete_firewall_rule_input import DeleteFirewallRuleInput as DeleteFirewallRuleInput
from hostafrica_sdk_python.models.delete_firewall_rule_output import DeleteFirewallRuleOutput as DeleteFirewallRuleOutput
from hostafrica_sdk_python.models.delete_firewall_rule_request_content import DeleteFirewallRuleRequestContent as DeleteFirewallRuleRequestContent
from hostafrica_sdk_python.models.delete_firewall_rule_response_content import DeleteFirewallRuleResponseContent as DeleteFirewallRuleResponseContent
from hostafrica_sdk_python.models.delete_notification_input import DeleteNotificationInput as DeleteNotificationInput
from hostafrica_sdk_python.models.delete_notification_output import DeleteNotificationOutput as DeleteNotificationOutput
from hostafrica_sdk_python.models.delete_notification_request_content import DeleteNotificationRequestContent as DeleteNotificationRequestContent
from hostafrica_sdk_python.models.delete_notification_response_content import DeleteNotificationResponseContent as DeleteNotificationResponseContent
from hostafrica_sdk_python.models.delete_power_task_input import DeletePowerTaskInput as DeletePowerTaskInput
from hostafrica_sdk_python.models.delete_power_task_output import DeletePowerTaskOutput as DeletePowerTaskOutput
from hostafrica_sdk_python.models.delete_power_task_request_content import DeletePowerTaskRequestContent as DeletePowerTaskRequestContent
from hostafrica_sdk_python.models.delete_power_task_response_content import DeletePowerTaskResponseContent as DeletePowerTaskResponseContent
from hostafrica_sdk_python.models.delete_rdns_record_input import DeleteRdnsRecordInput as DeleteRdnsRecordInput
from hostafrica_sdk_python.models.delete_rdns_record_output import DeleteRdnsRecordOutput as DeleteRdnsRecordOutput
from hostafrica_sdk_python.models.delete_rdns_record_request_content import DeleteRdnsRecordRequestContent as DeleteRdnsRecordRequestContent
from hostafrica_sdk_python.models.delete_rdns_record_response_content import DeleteRdnsRecordResponseContent as DeleteRdnsRecordResponseContent
from hostafrica_sdk_python.models.delete_snapshot_input import DeleteSnapshotInput as DeleteSnapshotInput
from hostafrica_sdk_python.models.delete_snapshot_output import DeleteSnapshotOutput as DeleteSnapshotOutput
from hostafrica_sdk_python.models.delete_snapshot_request_content import DeleteSnapshotRequestContent as DeleteSnapshotRequestContent
from hostafrica_sdk_python.models.delete_snapshot_response_content import DeleteSnapshotResponseContent as DeleteSnapshotResponseContent
from hostafrica_sdk_python.models.edit_backup_schedule_input import EditBackupScheduleInput as EditBackupScheduleInput
from hostafrica_sdk_python.models.edit_backup_schedule_output import EditBackupScheduleOutput as EditBackupScheduleOutput
from hostafrica_sdk_python.models.edit_backup_schedule_request_content import EditBackupScheduleRequestContent as EditBackupScheduleRequestContent
from hostafrica_sdk_python.models.edit_backup_schedule_response_content import EditBackupScheduleResponseContent as EditBackupScheduleResponseContent
from hostafrica_sdk_python.models.firewall_list_response_data import FirewallListResponseData as FirewallListResponseData
from hostafrica_sdk_python.models.firewall_move_direction import FirewallMoveDirection as FirewallMoveDirection
from hostafrica_sdk_python.models.firewall_move_response_data import FirewallMoveResponseData as FirewallMoveResponseData
from hostafrica_sdk_python.models.firewall_option import FirewallOption as FirewallOption
from hostafrica_sdk_python.models.firewall_rule import FirewallRule as FirewallRule
from hostafrica_sdk_python.models.firewall_rule_action import FirewallRuleAction as FirewallRuleAction
from hostafrica_sdk_python.models.firewall_rule_type import FirewallRuleType as FirewallRuleType
from hostafrica_sdk_python.models.forbidden_error import ForbiddenError as ForbiddenError
from hostafrica_sdk_python.models.forbidden_error_response_content import ForbiddenErrorResponseContent as ForbiddenErrorResponseContent
from hostafrica_sdk_python.models.get_catalogue_input import GetCatalogueInput as GetCatalogueInput
from hostafrica_sdk_python.models.get_catalogue_output import GetCatalogueOutput as GetCatalogueOutput
from hostafrica_sdk_python.models.get_catalogue_request_content import GetCatalogueRequestContent as GetCatalogueRequestContent
from hostafrica_sdk_python.models.get_catalogue_response_content import GetCatalogueResponseContent as GetCatalogueResponseContent
from hostafrica_sdk_python.models.get_no_vnc_console_input import GetNoVncConsoleInput as GetNoVncConsoleInput
from hostafrica_sdk_python.models.get_no_vnc_console_output import GetNoVncConsoleOutput as GetNoVncConsoleOutput
from hostafrica_sdk_python.models.get_no_vnc_console_request_content import GetNoVncConsoleRequestContent as GetNoVncConsoleRequestContent
from hostafrica_sdk_python.models.get_no_vnc_console_response_content import GetNoVncConsoleResponseContent as GetNoVncConsoleResponseContent
from hostafrica_sdk_python.models.get_os_template_details_input import GetOsTemplateDetailsInput as GetOsTemplateDetailsInput
from hostafrica_sdk_python.models.get_os_template_details_output import GetOsTemplateDetailsOutput as GetOsTemplateDetailsOutput
from hostafrica_sdk_python.models.get_os_template_details_request_content import GetOsTemplateDetailsRequestContent as GetOsTemplateDetailsRequestContent
from hostafrica_sdk_python.models.get_os_template_details_response_content import GetOsTemplateDetailsResponseContent as GetOsTemplateDetailsResponseContent
from hostafrica_sdk_python.models.get_os_template_details_response_data import GetOsTemplateDetailsResponseData as GetOsTemplateDetailsResponseData
from hostafrica_sdk_python.models.get_private_ssh_key_input import GetPrivateSshKeyInput as GetPrivateSshKeyInput
from hostafrica_sdk_python.models.get_private_ssh_key_output import GetPrivateSshKeyOutput as GetPrivateSshKeyOutput
from hostafrica_sdk_python.models.get_private_ssh_key_request_content import GetPrivateSshKeyRequestContent as GetPrivateSshKeyRequestContent
from hostafrica_sdk_python.models.get_private_ssh_key_response_content import GetPrivateSshKeyResponseContent as GetPrivateSshKeyResponseContent
from hostafrica_sdk_python.models.get_public_ssh_key_input import GetPublicSshKeyInput as GetPublicSshKeyInput
from hostafrica_sdk_python.models.get_public_ssh_key_output import GetPublicSshKeyOutput as GetPublicSshKeyOutput
from hostafrica_sdk_python.models.get_public_ssh_key_request_content import GetPublicSshKeyRequestContent as GetPublicSshKeyRequestContent
from hostafrica_sdk_python.models.get_public_ssh_key_response_content import GetPublicSshKeyResponseContent as GetPublicSshKeyResponseContent
from hostafrica_sdk_python.models.get_vps_config_input import GetVpsConfigInput as GetVpsConfigInput
from hostafrica_sdk_python.models.get_vps_config_output import GetVpsConfigOutput as GetVpsConfigOutput
from hostafrica_sdk_python.models.get_vps_config_request_content import GetVpsConfigRequestContent as GetVpsConfigRequestContent
from hostafrica_sdk_python.models.get_vps_config_response_content import GetVpsConfigResponseContent as GetVpsConfigResponseContent
from hostafrica_sdk_python.models.get_vps_details_input import GetVpsDetailsInput as GetVpsDetailsInput
from hostafrica_sdk_python.models.get_vps_details_output import GetVpsDetailsOutput as GetVpsDetailsOutput
from hostafrica_sdk_python.models.get_vps_details_request_content import GetVpsDetailsRequestContent as GetVpsDetailsRequestContent
from hostafrica_sdk_python.models.get_vps_details_response_content import GetVpsDetailsResponseContent as GetVpsDetailsResponseContent
from hostafrica_sdk_python.models.internal_service_error import InternalServiceError as InternalServiceError
from hostafrica_sdk_python.models.internal_service_error_response_content import InternalServiceErrorResponseContent as InternalServiceErrorResponseContent
from hostafrica_sdk_python.models.invalid_state_error import InvalidStateError as InvalidStateError
from hostafrica_sdk_python.models.invalid_state_error_response_content import InvalidStateErrorResponseContent as InvalidStateErrorResponseContent
from hostafrica_sdk_python.models.list_allowed_features_input import ListAllowedFeaturesInput as ListAllowedFeaturesInput
from hostafrica_sdk_python.models.list_allowed_features_output import ListAllowedFeaturesOutput as ListAllowedFeaturesOutput
from hostafrica_sdk_python.models.list_allowed_features_request_content import ListAllowedFeaturesRequestContent as ListAllowedFeaturesRequestContent
from hostafrica_sdk_python.models.list_allowed_features_response_content import ListAllowedFeaturesResponseContent as ListAllowedFeaturesResponseContent
from hostafrica_sdk_python.models.list_backup_schedules_input import ListBackupSchedulesInput as ListBackupSchedulesInput
from hostafrica_sdk_python.models.list_backup_schedules_output import ListBackupSchedulesOutput as ListBackupSchedulesOutput
from hostafrica_sdk_python.models.list_backup_schedules_request_content import ListBackupSchedulesRequestContent as ListBackupSchedulesRequestContent
from hostafrica_sdk_python.models.list_backup_schedules_response_content import ListBackupSchedulesResponseContent as ListBackupSchedulesResponseContent
from hostafrica_sdk_python.models.list_backups_input import ListBackupsInput as ListBackupsInput
from hostafrica_sdk_python.models.list_backups_output import ListBackupsOutput as ListBackupsOutput
from hostafrica_sdk_python.models.list_backups_request_content import ListBackupsRequestContent as ListBackupsRequestContent
from hostafrica_sdk_python.models.list_backups_response_content import ListBackupsResponseContent as ListBackupsResponseContent
from hostafrica_sdk_python.models.list_firewall_rules_input import ListFirewallRulesInput as ListFirewallRulesInput
from hostafrica_sdk_python.models.list_firewall_rules_output import ListFirewallRulesOutput as ListFirewallRulesOutput
from hostafrica_sdk_python.models.list_firewall_rules_request_content import ListFirewallRulesRequestContent as ListFirewallRulesRequestContent
from hostafrica_sdk_python.models.list_firewall_rules_response_content import ListFirewallRulesResponseContent as ListFirewallRulesResponseContent
from hostafrica_sdk_python.models.list_isos_input import ListIsosInput as ListIsosInput
from hostafrica_sdk_python.models.list_isos_output import ListIsosOutput as ListIsosOutput
from hostafrica_sdk_python.models.list_isos_request_content import ListIsosRequestContent as ListIsosRequestContent
from hostafrica_sdk_python.models.list_isos_response_content import ListIsosResponseContent as ListIsosResponseContent
from hostafrica_sdk_python.models.list_isos_response_data import ListIsosResponseData as ListIsosResponseData
from hostafrica_sdk_python.models.list_notifications_input import ListNotificationsInput as ListNotificationsInput
from hostafrica_sdk_python.models.list_notifications_output import ListNotificationsOutput as ListNotificationsOutput
from hostafrica_sdk_python.models.list_notifications_request_content import ListNotificationsRequestContent as ListNotificationsRequestContent
from hostafrica_sdk_python.models.list_notifications_response_content import ListNotificationsResponseContent as ListNotificationsResponseContent
from hostafrica_sdk_python.models.list_orders_output import ListOrdersOutput as ListOrdersOutput
from hostafrica_sdk_python.models.list_orders_response_content import ListOrdersResponseContent as ListOrdersResponseContent
from hostafrica_sdk_python.models.list_orders_response_data import ListOrdersResponseData as ListOrdersResponseData
from hostafrica_sdk_python.models.list_os_templates_input import ListOsTemplatesInput as ListOsTemplatesInput
from hostafrica_sdk_python.models.list_os_templates_output import ListOsTemplatesOutput as ListOsTemplatesOutput
from hostafrica_sdk_python.models.list_os_templates_request_content import ListOsTemplatesRequestContent as ListOsTemplatesRequestContent
from hostafrica_sdk_python.models.list_os_templates_response_content import ListOsTemplatesResponseContent as ListOsTemplatesResponseContent
from hostafrica_sdk_python.models.list_os_templates_response_data import ListOsTemplatesResponseData as ListOsTemplatesResponseData
from hostafrica_sdk_python.models.list_power_tasks_input import ListPowerTasksInput as ListPowerTasksInput
from hostafrica_sdk_python.models.list_power_tasks_output import ListPowerTasksOutput as ListPowerTasksOutput
from hostafrica_sdk_python.models.list_power_tasks_request_content import ListPowerTasksRequestContent as ListPowerTasksRequestContent
from hostafrica_sdk_python.models.list_power_tasks_response_content import ListPowerTasksResponseContent as ListPowerTasksResponseContent
from hostafrica_sdk_python.models.list_rdns_records_output import ListRdnsRecordsOutput as ListRdnsRecordsOutput
from hostafrica_sdk_python.models.list_rdns_records_response_content import ListRdnsRecordsResponseContent as ListRdnsRecordsResponseContent
from hostafrica_sdk_python.models.list_rdns_response_data import ListRdnsResponseData as ListRdnsResponseData
from hostafrica_sdk_python.models.list_reinstall_os_input import ListReinstallOsInput as ListReinstallOsInput
from hostafrica_sdk_python.models.list_reinstall_os_output import ListReinstallOsOutput as ListReinstallOsOutput
from hostafrica_sdk_python.models.list_reinstall_os_request_content import ListReinstallOsRequestContent as ListReinstallOsRequestContent
from hostafrica_sdk_python.models.list_reinstall_os_response_content import ListReinstallOsResponseContent as ListReinstallOsResponseContent
from hostafrica_sdk_python.models.list_reinstall_os_response_data import ListReinstallOsResponseData as ListReinstallOsResponseData
from hostafrica_sdk_python.models.list_snapshots_input import ListSnapshotsInput as ListSnapshotsInput
from hostafrica_sdk_python.models.list_snapshots_output import ListSnapshotsOutput as ListSnapshotsOutput
from hostafrica_sdk_python.models.list_snapshots_request_content import ListSnapshotsRequestContent as ListSnapshotsRequestContent
from hostafrica_sdk_python.models.list_snapshots_response_content import ListSnapshotsResponseContent as ListSnapshotsResponseContent
from hostafrica_sdk_python.models.list_vps_services_data import ListVpsServicesData as ListVpsServicesData
from hostafrica_sdk_python.models.list_vps_services_output import ListVpsServicesOutput as ListVpsServicesOutput
from hostafrica_sdk_python.models.list_vps_services_response_content import ListVpsServicesResponseContent as ListVpsServicesResponseContent
from hostafrica_sdk_python.models.mount_iso_input import MountIsoInput as MountIsoInput
from hostafrica_sdk_python.models.mount_iso_output import MountIsoOutput as MountIsoOutput
from hostafrica_sdk_python.models.mount_iso_request_content import MountIsoRequestContent as MountIsoRequestContent
from hostafrica_sdk_python.models.mount_iso_response_content import MountIsoResponseContent as MountIsoResponseContent
from hostafrica_sdk_python.models.move_firewall_rule_input import MoveFirewallRuleInput as MoveFirewallRuleInput
from hostafrica_sdk_python.models.move_firewall_rule_output import MoveFirewallRuleOutput as MoveFirewallRuleOutput
from hostafrica_sdk_python.models.move_firewall_rule_request_content import MoveFirewallRuleRequestContent as MoveFirewallRuleRequestContent
from hostafrica_sdk_python.models.move_firewall_rule_response_content import MoveFirewallRuleResponseContent as MoveFirewallRuleResponseContent
from hostafrica_sdk_python.models.no_vnc_console_details import NoVncConsoleDetails as NoVncConsoleDetails
from hostafrica_sdk_python.models.no_vnc_console_response_data import NoVncConsoleResponseData as NoVncConsoleResponseData
from hostafrica_sdk_python.models.notification import Notification as Notification
from hostafrica_sdk_python.models.notification_create_response_data import NotificationCreateResponseData as NotificationCreateResponseData
from hostafrica_sdk_python.models.notification_dialog_rules import NotificationDialogRules as NotificationDialogRules
from hostafrica_sdk_python.models.notification_list_response_data import NotificationListResponseData as NotificationListResponseData
from hostafrica_sdk_python.models.notification_status import NotificationStatus as NotificationStatus
from hostafrica_sdk_python.models.operation_status import OperationStatus as OperationStatus
from hostafrica_sdk_python.models.order import Order as Order
from hostafrica_sdk_python.models.order_last_attempt import OrderLastAttempt as OrderLastAttempt
from hostafrica_sdk_python.models.order_warning import OrderWarning as OrderWarning
from hostafrica_sdk_python.models.os_image import OsImage as OsImage
from hostafrica_sdk_python.models.payment_error import PaymentError as PaymentError
from hostafrica_sdk_python.models.payment_status import PaymentStatus as PaymentStatus
from hostafrica_sdk_python.models.power_task import PowerTask as PowerTask
from hostafrica_sdk_python.models.power_task_create_response_data import PowerTaskCreateResponseData as PowerTaskCreateResponseData
from hostafrica_sdk_python.models.power_task_dialog_rules import PowerTaskDialogRules as PowerTaskDialogRules
from hostafrica_sdk_python.models.power_task_list_response_data import PowerTaskListResponseData as PowerTaskListResponseData
from hostafrica_sdk_python.models.public_ssh_key_response_data import PublicSshKeyResponseData as PublicSshKeyResponseData
from hostafrica_sdk_python.models.rdns_available_item import RdnsAvailableItem as RdnsAvailableItem
from hostafrica_sdk_python.models.rdns_pool import RdnsPool as RdnsPool
from hostafrica_sdk_python.models.rdns_record import RdnsRecord as RdnsRecord
from hostafrica_sdk_python.models.reboot_vps_input import RebootVpsInput as RebootVpsInput
from hostafrica_sdk_python.models.reboot_vps_output import RebootVpsOutput as RebootVpsOutput
from hostafrica_sdk_python.models.reboot_vps_request_content import RebootVpsRequestContent as RebootVpsRequestContent
from hostafrica_sdk_python.models.reboot_vps_response_content import RebootVpsResponseContent as RebootVpsResponseContent
from hostafrica_sdk_python.models.resource_not_found_error import ResourceNotFoundError as ResourceNotFoundError
from hostafrica_sdk_python.models.resource_not_found_error_response_content import ResourceNotFoundErrorResponseContent as ResourceNotFoundErrorResponseContent
from hostafrica_sdk_python.models.restore_backup_input import RestoreBackupInput as RestoreBackupInput
from hostafrica_sdk_python.models.restore_backup_output import RestoreBackupOutput as RestoreBackupOutput
from hostafrica_sdk_python.models.restore_backup_request_content import RestoreBackupRequestContent as RestoreBackupRequestContent
from hostafrica_sdk_python.models.restore_backup_response_content import RestoreBackupResponseContent as RestoreBackupResponseContent
from hostafrica_sdk_python.models.retry_payment_input import RetryPaymentInput as RetryPaymentInput
from hostafrica_sdk_python.models.retry_payment_output import RetryPaymentOutput as RetryPaymentOutput
from hostafrica_sdk_python.models.retry_payment_request_content import RetryPaymentRequestContent as RetryPaymentRequestContent
from hostafrica_sdk_python.models.retry_payment_response_content import RetryPaymentResponseContent as RetryPaymentResponseContent
from hostafrica_sdk_python.models.retry_payment_response_data import RetryPaymentResponseData as RetryPaymentResponseData
from hostafrica_sdk_python.models.retry_payment_total import RetryPaymentTotal as RetryPaymentTotal
from hostafrica_sdk_python.models.rollback_snapshot_input import RollbackSnapshotInput as RollbackSnapshotInput
from hostafrica_sdk_python.models.rollback_snapshot_output import RollbackSnapshotOutput as RollbackSnapshotOutput
from hostafrica_sdk_python.models.rollback_snapshot_request_content import RollbackSnapshotRequestContent as RollbackSnapshotRequestContent
from hostafrica_sdk_python.models.rollback_snapshot_response_content import RollbackSnapshotResponseContent as RollbackSnapshotResponseContent
from hostafrica_sdk_python.models.service_backups_response_data import ServiceBackupsResponseData as ServiceBackupsResponseData
from hostafrica_sdk_python.models.service_snapshots_response_data import ServiceSnapshotsResponseData as ServiceSnapshotsResponseData
from hostafrica_sdk_python.models.service_unavailable_error import ServiceUnavailableError as ServiceUnavailableError
from hostafrica_sdk_python.models.service_unavailable_error_response_content import ServiceUnavailableErrorResponseContent as ServiceUnavailableErrorResponseContent
from hostafrica_sdk_python.models.shutdown_vps_input import ShutdownVpsInput as ShutdownVpsInput
from hostafrica_sdk_python.models.shutdown_vps_output import ShutdownVpsOutput as ShutdownVpsOutput
from hostafrica_sdk_python.models.shutdown_vps_request_content import ShutdownVpsRequestContent as ShutdownVpsRequestContent
from hostafrica_sdk_python.models.shutdown_vps_response_content import ShutdownVpsResponseContent as ShutdownVpsResponseContent
from hostafrica_sdk_python.models.snapshot_create_response_data import SnapshotCreateResponseData as SnapshotCreateResponseData
from hostafrica_sdk_python.models.snapshot_item import SnapshotItem as SnapshotItem
from hostafrica_sdk_python.models.ssh_key_details import SshKeyDetails as SshKeyDetails
from hostafrica_sdk_python.models.start_vps_input import StartVpsInput as StartVpsInput
from hostafrica_sdk_python.models.start_vps_output import StartVpsOutput as StartVpsOutput
from hostafrica_sdk_python.models.start_vps_request_content import StartVpsRequestContent as StartVpsRequestContent
from hostafrica_sdk_python.models.start_vps_response_content import StartVpsResponseContent as StartVpsResponseContent
from hostafrica_sdk_python.models.stop_vps_input import StopVpsInput as StopVpsInput
from hostafrica_sdk_python.models.stop_vps_output import StopVpsOutput as StopVpsOutput
from hostafrica_sdk_python.models.stop_vps_request_content import StopVpsRequestContent as StopVpsRequestContent
from hostafrica_sdk_python.models.stop_vps_response_content import StopVpsResponseContent as StopVpsResponseContent
from hostafrica_sdk_python.models.suspend_vps_input import SuspendVpsInput as SuspendVpsInput
from hostafrica_sdk_python.models.suspend_vps_output import SuspendVpsOutput as SuspendVpsOutput
from hostafrica_sdk_python.models.suspend_vps_request_content import SuspendVpsRequestContent as SuspendVpsRequestContent
from hostafrica_sdk_python.models.suspend_vps_response_content import SuspendVpsResponseContent as SuspendVpsResponseContent
from hostafrica_sdk_python.models.terminate_vps_input import TerminateVpsInput as TerminateVpsInput
from hostafrica_sdk_python.models.terminate_vps_output import TerminateVpsOutput as TerminateVpsOutput
from hostafrica_sdk_python.models.terminate_vps_request_content import TerminateVpsRequestContent as TerminateVpsRequestContent
from hostafrica_sdk_python.models.terminate_vps_response_content import TerminateVpsResponseContent as TerminateVpsResponseContent
from hostafrica_sdk_python.models.too_many_requests_error import TooManyRequestsError as TooManyRequestsError
from hostafrica_sdk_python.models.too_many_requests_error_response_content import TooManyRequestsErrorResponseContent as TooManyRequestsErrorResponseContent
from hostafrica_sdk_python.models.trigger_reinstall_input import TriggerReinstallInput as TriggerReinstallInput
from hostafrica_sdk_python.models.trigger_reinstall_output import TriggerReinstallOutput as TriggerReinstallOutput
from hostafrica_sdk_python.models.trigger_reinstall_request_content import TriggerReinstallRequestContent as TriggerReinstallRequestContent
from hostafrica_sdk_python.models.trigger_reinstall_response_content import TriggerReinstallResponseContent as TriggerReinstallResponseContent
from hostafrica_sdk_python.models.trigger_reinstall_response_data import TriggerReinstallResponseData as TriggerReinstallResponseData
from hostafrica_sdk_python.models.unauthorized_error import UnauthorizedError as UnauthorizedError
from hostafrica_sdk_python.models.unauthorized_error_response_content import UnauthorizedErrorResponseContent as UnauthorizedErrorResponseContent
from hostafrica_sdk_python.models.unsuspend_vps_input import UnsuspendVpsInput as UnsuspendVpsInput
from hostafrica_sdk_python.models.unsuspend_vps_output import UnsuspendVpsOutput as UnsuspendVpsOutput
from hostafrica_sdk_python.models.unsuspend_vps_request_content import UnsuspendVpsRequestContent as UnsuspendVpsRequestContent
from hostafrica_sdk_python.models.unsuspend_vps_response_content import UnsuspendVpsResponseContent as UnsuspendVpsResponseContent
from hostafrica_sdk_python.models.update_firewall_rule_input import UpdateFirewallRuleInput as UpdateFirewallRuleInput
from hostafrica_sdk_python.models.update_firewall_rule_output import UpdateFirewallRuleOutput as UpdateFirewallRuleOutput
from hostafrica_sdk_python.models.update_firewall_rule_request_content import UpdateFirewallRuleRequestContent as UpdateFirewallRuleRequestContent
from hostafrica_sdk_python.models.update_firewall_rule_response_content import UpdateFirewallRuleResponseContent as UpdateFirewallRuleResponseContent
from hostafrica_sdk_python.models.update_notification_input import UpdateNotificationInput as UpdateNotificationInput
from hostafrica_sdk_python.models.update_notification_output import UpdateNotificationOutput as UpdateNotificationOutput
from hostafrica_sdk_python.models.update_notification_request_content import UpdateNotificationRequestContent as UpdateNotificationRequestContent
from hostafrica_sdk_python.models.update_notification_response_content import UpdateNotificationResponseContent as UpdateNotificationResponseContent
from hostafrica_sdk_python.models.update_power_task_input import UpdatePowerTaskInput as UpdatePowerTaskInput
from hostafrica_sdk_python.models.update_power_task_output import UpdatePowerTaskOutput as UpdatePowerTaskOutput
from hostafrica_sdk_python.models.update_power_task_request_content import UpdatePowerTaskRequestContent as UpdatePowerTaskRequestContent
from hostafrica_sdk_python.models.update_power_task_response_content import UpdatePowerTaskResponseContent as UpdatePowerTaskResponseContent
from hostafrica_sdk_python.models.update_snapshot_input import UpdateSnapshotInput as UpdateSnapshotInput
from hostafrica_sdk_python.models.update_snapshot_output import UpdateSnapshotOutput as UpdateSnapshotOutput
from hostafrica_sdk_python.models.update_snapshot_request_content import UpdateSnapshotRequestContent as UpdateSnapshotRequestContent
from hostafrica_sdk_python.models.update_snapshot_response_content import UpdateSnapshotResponseContent as UpdateSnapshotResponseContent
from hostafrica_sdk_python.models.update_ssh_keys_input import UpdateSshKeysInput as UpdateSshKeysInput
from hostafrica_sdk_python.models.update_ssh_keys_output import UpdateSshKeysOutput as UpdateSshKeysOutput
from hostafrica_sdk_python.models.update_ssh_keys_request_content import UpdateSshKeysRequestContent as UpdateSshKeysRequestContent
from hostafrica_sdk_python.models.update_ssh_keys_response_content import UpdateSshKeysResponseContent as UpdateSshKeysResponseContent
from hostafrica_sdk_python.models.update_vps_config_input import UpdateVpsConfigInput as UpdateVpsConfigInput
from hostafrica_sdk_python.models.update_vps_config_output import UpdateVpsConfigOutput as UpdateVpsConfigOutput
from hostafrica_sdk_python.models.update_vps_config_request_content import UpdateVpsConfigRequestContent as UpdateVpsConfigRequestContent
from hostafrica_sdk_python.models.update_vps_config_response_content import UpdateVpsConfigResponseContent as UpdateVpsConfigResponseContent
from hostafrica_sdk_python.models.user_change_password_details import UserChangePasswordDetails as UserChangePasswordDetails
from hostafrica_sdk_python.models.user_change_password_input import UserChangePasswordInput as UserChangePasswordInput
from hostafrica_sdk_python.models.user_change_password_output import UserChangePasswordOutput as UserChangePasswordOutput
from hostafrica_sdk_python.models.user_change_password_request_content import UserChangePasswordRequestContent as UserChangePasswordRequestContent
from hostafrica_sdk_python.models.user_change_password_response_content import UserChangePasswordResponseContent as UserChangePasswordResponseContent
from hostafrica_sdk_python.models.user_change_password_response_data import UserChangePasswordResponseData as UserChangePasswordResponseData
from hostafrica_sdk_python.models.validate_pricing_base import ValidatePricingBase as ValidatePricingBase
from hostafrica_sdk_python.models.validate_pricing_breakdown import ValidatePricingBreakdown as ValidatePricingBreakdown
from hostafrica_sdk_python.models.validate_pricing_config_item import ValidatePricingConfigItem as ValidatePricingConfigItem
from hostafrica_sdk_python.models.validate_pricing_currency import ValidatePricingCurrency as ValidatePricingCurrency
from hostafrica_sdk_python.models.validate_pricing_discount import ValidatePricingDiscount as ValidatePricingDiscount
from hostafrica_sdk_python.models.validate_pricing_input import ValidatePricingInput as ValidatePricingInput
from hostafrica_sdk_python.models.validate_pricing_output import ValidatePricingOutput as ValidatePricingOutput
from hostafrica_sdk_python.models.validate_pricing_plan_config import ValidatePricingPlanConfig as ValidatePricingPlanConfig
from hostafrica_sdk_python.models.validate_pricing_plan_pricing import ValidatePricingPlanPricing as ValidatePricingPlanPricing
from hostafrica_sdk_python.models.validate_pricing_price_range import ValidatePricingPriceRange as ValidatePricingPriceRange
from hostafrica_sdk_python.models.validate_pricing_product import ValidatePricingProduct as ValidatePricingProduct
from hostafrica_sdk_python.models.validate_pricing_product_result import ValidatePricingProductResult as ValidatePricingProductResult
from hostafrica_sdk_python.models.validate_pricing_prorata import ValidatePricingProrata as ValidatePricingProrata
from hostafrica_sdk_python.models.validate_pricing_request_content import ValidatePricingRequestContent as ValidatePricingRequestContent
from hostafrica_sdk_python.models.validate_pricing_response_content import ValidatePricingResponseContent as ValidatePricingResponseContent
from hostafrica_sdk_python.models.validate_pricing_response_data import ValidatePricingResponseData as ValidatePricingResponseData
from hostafrica_sdk_python.models.validate_pricing_summary import ValidatePricingSummary as ValidatePricingSummary
from hostafrica_sdk_python.models.validate_pricing_summary_recurring import ValidatePricingSummaryRecurring as ValidatePricingSummaryRecurring
from hostafrica_sdk_python.models.validation_error import ValidationError as ValidationError
from hostafrica_sdk_python.models.validation_error_response_content import ValidationErrorResponseContent as ValidationErrorResponseContent
from hostafrica_sdk_python.models.vps_available_features import VpsAvailableFeatures as VpsAvailableFeatures
from hostafrica_sdk_python.models.vps_bandwidth_info import VpsBandwidthInfo as VpsBandwidthInfo
from hostafrica_sdk_python.models.vps_config_response_data import VpsConfigResponseData as VpsConfigResponseData
from hostafrica_sdk_python.models.vps_cpu_info import VpsCpuInfo as VpsCpuInfo
from hostafrica_sdk_python.models.vps_credentials import VpsCredentials as VpsCredentials
from hostafrica_sdk_python.models.vps_details_response import VpsDetailsResponse as VpsDetailsResponse
from hostafrica_sdk_python.models.vps_disk_info import VpsDiskInfo as VpsDiskInfo
from hostafrica_sdk_python.models.vps_memory_info import VpsMemoryInfo as VpsMemoryInfo
from hostafrica_sdk_python.models.vps_network_rate import VpsNetworkRate as VpsNetworkRate
from hostafrica_sdk_python.models.vps_os_info import VpsOsInfo as VpsOsInfo
from hostafrica_sdk_python.models.vps_service_info import VpsServiceInfo as VpsServiceInfo
from hostafrica_sdk_python.models.vps_simple_action_response_data import VpsSimpleActionResponseData as VpsSimpleActionResponseData
from hostafrica_sdk_python.models.vps_vm_info import VpsVmInfo as VpsVmInfo

