# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class CreateOrderDomainItem(BaseModel):
    """
    A domain line item returned in the order response
    """ # noqa: E501
    line_id: StrictInt = Field(description="Line item identifier")
    domain_id: StrictInt = Field(description="Domain identifier")
    domain: StrictStr = Field(description="Domain name")
    type: StrictStr = Field(description="Domain operation type (e.g. register, transfer)")
    period: StrictInt = Field(description="Registration period in years")
    domain_warranty: StrictBool = Field(description="Whether domain warranty is included")
    autorenew: StrictBool = Field(description="Whether auto-renewal is enabled")
    amount: StrictStr = Field(description="Line item amount charged (decimal string, e.g. \"2333.33\")")
    __properties: ClassVar[List[str]] = ["line_id", "domain_id", "domain", "type", "period", "domain_warranty", "autorenew", "amount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrderDomainItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrderDomainItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "line_id": obj.get("line_id"),
            "domain_id": obj.get("domain_id"),
            "domain": obj.get("domain"),
            "type": obj.get("type"),
            "period": obj.get("period"),
            "domain_warranty": obj.get("domain_warranty"),
            "autorenew": obj.get("autorenew"),
            "amount": obj.get("amount")
        })
        return _obj


