# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hostafrica_sdk_python.models.notification_status import NotificationStatus
from typing import Optional, Set
from typing_extensions import Self

class CreateNotificationRequestContent(BaseModel):
    """
    CreateNotificationRequestContent
    """ # noqa: E501
    service_id: StrictStr = Field(description="Service ID - must be sent as a string")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Name/title for the notification")
    status: Optional[NotificationStatus] = None
    notification_interval: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Notification interval in minutes (must be > 0)")
    data_timeframe: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Data timeframe in minutes (must be > 0)")
    exceed_all: Optional[StrictBool] = Field(default=None, description="Whether all thresholds must be exceeded (true) or any one (false)")
    email_address: Optional[List[StrictStr]] = Field(default=None, description="Email addresses for notifications (comma-separated string or array)")
    cpu_usage: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="CPU usage threshold percentage (0-100)")
    memory_usage: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Memory usage threshold percentage (0-100)")
    network_traffic: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Network traffic threshold percentage (0-100)")
    disk_read: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Disk read threshold percentage (0-100)")
    disk_write: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Disk write threshold percentage (0-100)")
    __properties: ClassVar[List[str]] = ["service_id", "name", "status", "notification_interval", "data_timeframe", "exceed_all", "email_address", "cpu_usage", "memory_usage", "network_traffic", "disk_read", "disk_write"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateNotificationRequestContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateNotificationRequestContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "service_id": obj.get("service_id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "notification_interval": obj.get("notification_interval"),
            "data_timeframe": obj.get("data_timeframe"),
            "exceed_all": obj.get("exceed_all"),
            "email_address": obj.get("email_address"),
            "cpu_usage": obj.get("cpu_usage"),
            "memory_usage": obj.get("memory_usage"),
            "network_traffic": obj.get("network_traffic"),
            "disk_read": obj.get("disk_read"),
            "disk_write": obj.get("disk_write")
        })
        return _obj


