# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PowerTask(BaseModel):
    """
    Individual power task item
    """ # noqa: E501
    id: StrictInt = Field(description="Task ID")
    hosting_id: StrictInt = Field(description="Hosting/service ID")
    description: Optional[StrictStr] = Field(default=None, description="Task description")
    action: StrictStr = Field(description="Power action (start, stop, restart)")
    start: StrictStr = Field(description="Task start date/time (ISO 8601 format)")
    end: Optional[StrictStr] = Field(default=None, description="Task end date/time (ISO 8601 format, null if no end)")
    job_type: StrictStr = Field(description="Job type (oneTime, daily, weekly)")
    job_time: StrictStr = Field(description="Job execution time (HH:MM:SS format)")
    days: List[StrictStr] = Field(description="Days of week for weekly jobs (empty array for oneTime/daily)")
    last_run: Optional[StrictStr] = Field(default=None, description="Last run timestamp (null if never run)")
    __properties: ClassVar[List[str]] = ["id", "hosting_id", "description", "action", "start", "end", "job_type", "job_time", "days", "last_run"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PowerTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PowerTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "hosting_id": obj.get("hosting_id"),
            "description": obj.get("description"),
            "action": obj.get("action"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "job_type": obj.get("job_type"),
            "job_time": obj.get("job_time"),
            "days": obj.get("days"),
            "last_run": obj.get("last_run")
        })
        return _obj


