# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from hostafrica_sdk_python.models.rdns_pool import RdnsPool
from typing import Optional, Set
from typing_extensions import Self

class RdnsAvailableItem(BaseModel):
    """
    One service the client can manage PTRs for
    """ # noqa: E501
    type: StrictInt = Field(description="Zone type matching RdnsRecord.type")
    relid: StrictInt = Field(description="Related service identifier")
    name: StrictStr = Field(description="Display label for the service")
    ips: List[StrictStr] = Field(description="Concrete IP addresses available for this service")
    pools: List[RdnsPool] = Field(description="Subnet pools available when subnet_custom_ip_mode is on")
    ptr_limit: StrictInt = Field(description="Per-package PTR limit (-1 = unlimited)")
    server_id: StrictInt
    allow_rdns: StrictBool = Field(description="Server has ALLOW_RDNS=on")
    rdns_supported: StrictBool = Field(description="Server module supports rDNS")
    __properties: ClassVar[List[str]] = ["type", "relid", "name", "ips", "pools", "ptr_limit", "server_id", "allow_rdns", "rdns_supported"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RdnsAvailableItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pools (list)
        _items = []
        if self.pools:
            for _item_pools in self.pools:
                if _item_pools:
                    _items.append(_item_pools.to_dict())
            _dict['pools'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RdnsAvailableItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "relid": obj.get("relid"),
            "name": obj.get("name"),
            "ips": obj.get("ips"),
            "pools": [RdnsPool.from_dict(_item) for _item in obj["pools"]] if obj.get("pools") is not None else None,
            "ptr_limit": obj.get("ptr_limit"),
            "server_id": obj.get("server_id"),
            "allow_rdns": obj.get("allow_rdns"),
            "rdns_supported": obj.get("rdns_supported")
        })
        return _obj


