# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from hostafrica_sdk_python.models.validate_pricing_currency import ValidatePricingCurrency
from hostafrica_sdk_python.models.validate_pricing_product_result import ValidatePricingProductResult
from hostafrica_sdk_python.models.validate_pricing_summary import ValidatePricingSummary
from typing import Optional, Set
from typing_extensions import Self

class ValidatePricingResponseData(BaseModel):
    """
    Top-level data payload for the ValidatePricing response
    """ # noqa: E501
    currency: ValidatePricingCurrency
    products: List[ValidatePricingProductResult]
    summary: ValidatePricingSummary
    errors: List[StrictStr] = Field(description="List of strings")
    __properties: ClassVar[List[str]] = ["currency", "products", "summary", "errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidatePricingResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item_products in self.products:
                if _item_products:
                    _items.append(_item_products.to_dict())
            _dict['products'] = _items
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidatePricingResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": ValidatePricingCurrency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "products": [ValidatePricingProductResult.from_dict(_item) for _item in obj["products"]] if obj.get("products") is not None else None,
            "summary": ValidatePricingSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "errors": obj.get("errors")
        })
        return _obj


