# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hostafrica_sdk_python.models.validate_pricing_plan_config import ValidatePricingPlanConfig
from hostafrica_sdk_python.models.validate_pricing_plan_pricing import ValidatePricingPlanPricing
from typing import Optional, Set
from typing_extensions import Self

class ValidatePricingConfigItem(BaseModel):
    """
    A single configuration item in the pricing breakdown
    """ # noqa: E501
    option_id: Optional[StrictInt] = Field(default=None, description="Option ID (absent for plan-type items)")
    name: StrictStr
    type: StrictStr
    selected: Optional[Any]
    selected_name: Optional[StrictStr] = None
    plan_config: Optional[ValidatePricingPlanConfig] = None
    pricing: Optional[ValidatePricingPlanPricing] = None
    price: Optional[StrictStr] = None
    setup: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["option_id", "name", "type", "selected", "selected_name", "plan_config", "pricing", "price", "setup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidatePricingConfigItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plan_config
        if self.plan_config:
            _dict['plan_config'] = self.plan_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pricing
        if self.pricing:
            _dict['pricing'] = self.pricing.to_dict()
        # set to None if selected (nullable) is None
        # and model_fields_set contains the field
        if self.selected is None and "selected" in self.model_fields_set:
            _dict['selected'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidatePricingConfigItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "option_id": obj.get("option_id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "selected": obj.get("selected"),
            "selected_name": obj.get("selected_name"),
            "plan_config": ValidatePricingPlanConfig.from_dict(obj["plan_config"]) if obj.get("plan_config") is not None else None,
            "pricing": ValidatePricingPlanPricing.from_dict(obj["pricing"]) if obj.get("pricing") is not None else None,
            "price": obj.get("price"),
            "setup": obj.get("setup")
        })
        return _obj


