# coding: utf-8

"""
    HostAfricaApi

    HostAfrica API - Manages VPS instances and operations

    The version of the OpenAPI document: 2026-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VpsCancelType(str, Enum):
    """
    Cancel type enum - controls when a VPS service cancellation takes effect
    """

    """
    allowed enum values
    """
    IMMEDIATE = 'immediate'
    END_OF_BILLING_PERIOD = 'end_of_billing_period'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VpsCancelType from a JSON string"""
        return cls(json.loads(json_str))


